# Generated by Django 3.2.8 on 2022-08-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_document_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='./'),
        ),
    ]
